package com.zhizulx.tt.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import java.util.Date;

/**
 * Entity mapped to table cityInfo.
 */
public class DateEntity {
    private Date date;
    private int weekday;
    private int type;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DateEntity() {
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public int getWeekday() {
        return weekday;
    }

    public void setWeekday(int weekday) {
        this.weekday = weekday;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }
    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
