package com.zhizulx.tt.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table DetailDispInfo.
 */
public class DetailDispEntity {

    private Long id;
    private int dbID;
    private int type;
    /** Not-null value. */
    private String image;
    /** Not-null value. */
    private String title;
    /** Not-null value. */
    private String cityCode;
    /** Not-null value. */
    private String time;
    private int edited;
    private int version;
    private int status;
    private int created;
    private int updated;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DetailDispEntity() {
    }

    public DetailDispEntity(Long id) {
        this.id = id;
    }

    public DetailDispEntity(Long id, int dbID, int type, String image, String title, String cityCode, String time, int edited, int version, int status, int created, int updated) {
        this.id = id;
        this.dbID = dbID;
        this.type = type;
        this.image = image;
        this.title = title;
        this.cityCode = cityCode;
        this.time = time;
        this.edited = edited;
        this.version = version;
        this.status = status;
        this.created = created;
        this.updated = updated;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getDbID() {
        return dbID;
    }

    public void setDbID(int dbID) {
        this.dbID = dbID;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getImage() {
        return image;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImage(String image) {
        this.image = image;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    /** Not-null value. */
    public String getCityCode() {
        return cityCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    /** Not-null value. */
    public String getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(String time) {
        this.time = time;
    }

    public int getEdited() {
        return edited;
    }

    public void setEdited(int edited) {
        this.edited = edited;
    }

    public int getVersion() {
        return version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getCreated() {
        return created;
    }

    public void setCreated(int created) {
        this.created = created;
    }

    public int getUpdated() {
        return updated;
    }

    public void setUpdated(int updated) {
        this.updated = updated;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
