package com.zhizulx.tt.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import java.util.ArrayList;
import java.util.List;

/**
 * Entity mapped to table PlayConfigInfo.
 */
public class TravelCityEntity {

    private Long id;
    /** Not-null value. */
    private String cityName;
    private TrafficEntity go;
    private List<SightEntity> sightEntityList = new ArrayList<>();
    private List<HotelEntity> hotelEntityList = new ArrayList<>();
    private TrafficEntity back;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TravelCityEntity() {
    }

    /** Not-null value. */
    public String getCityName() {
        return cityName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /** Not-null value. */
    public TrafficEntity getGo() {
        return go;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGo(TrafficEntity go) {
        this.go = go;
    }

    /** Not-null value. */
    public List<SightEntity> getSightList() {
        return sightEntityList;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSightList(List<SightEntity> sightEntityList) {
        this.sightEntityList.clear();
        this.sightEntityList.addAll(sightEntityList);
    }

    public List<HotelEntity> getHotelList() {
        return hotelEntityList;
    }

    public void setHotelList(List<HotelEntity> hotelEntityList) {
        this.hotelEntityList = hotelEntityList;
    }

    /** Not-null value. */
    public TrafficEntity getBack() {
        return back;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBack(TrafficEntity back) {
        this.back = back;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
